#!/bin/sh
#!/bin/bash
#!/usr/bin/bash
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/bash
###############################################
Anlominus="Anlominus"
# Name : Anlominus ~ Linfo
# Description : Linfo ~ All In One Linux Commands
# Date : 2022 May
# Last UPDATE : 2022 June 15
# Aouther: Anlominus ~> RhytMix ~> Linfo
# Skils: Best Copywriter IN the COSMOS!
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE GREAT SCRIPTS
# CREDIT: To All World Creators free Scripts & Tools
# Location: Made With LOVE IN ISRAEL !
# Source: https://github.com/Anlominus/Linfo
###############################################
clear
# CODE Functions
# checking for system package manager

HacKingProColors(){
##############################################################################
# COLORS AND BACKGROUNDS
##############################################################################
Color_Off='\033[0m' # Text Reset

# Regular Colors
Black='\033[0;30m'  # Black
Red='\033[0;31m'    # Red
Green='\033[0;32m'  # Green
Yellow='\033[0;33m' # Yellow
Blue='\033[0;34m'   # Blue
Purple='\033[0;35m' # Purple
Cyan='\033[0;36m'   # Cyan
White='\033[0;97m'  # White

# Additional colors
LGrey='\033[0;37m'   # Ligth Gray
DGrey='\033[0;90m'   # Dark Gray
LRed='\033[0;91m'    # Ligth Red
LGreen='\033[0;92m'  # Ligth Green
LYellow='\033[0;93m' # Ligth Yellow
LBlue='\033[0;94m'   # Ligth Blue
LPurple='\033[0;95m' # Light Purple
LCyan='\033[0;96m'   # Ligth Cyan

# Bold
BBlack='\033[1;30m'  # Black
BRed='\033[1;31m'    # Red
BGreen='\033[1;32m'  # Green
BYellow='\033[1;33m' # Yellow
BBlue='\033[1;34m'   # Blue
BPurple='\033[1;35m' # Purple
BCyan='\033[1;36m'   # Cyan
BWhite='\033[1;37m'  # White

# Underline
UBlack='\033[4;30m'  # Black
URed='\033[4;31m'    # Red
UGreen='\033[4;32m'  # Green
UYellow='\033[4;33m' # Yellow
UBlue='\033[4;34m'   # Blue
UPurple='\033[4;35m' # Purple
UCyan='\033[4;36m'   # Cyan
UWhite='\033[4;37m'  # White

# Background
On_Black='\033[40m'  # Black
On_Red='\033[41m'    # Red
On_Green='\033[42m'  # Green
On_Yellow='\033[43m' # Yellow
On_Blue='\033[44m'   # Blue
On_Purple='\033[45m' # Purple
On_Cyan='\033[46m'   # Cyan
On_White='\033[47m'  # White
}
HacKingProColors

echo "\n\t\t ${LPurple} Linux Commands Cheat Sheet.\n"
echo "\n\t\t ${LGreen} All Useful ${LBlue}Linux Commands ${LGreen}In One Place\n"
echo "\n\t\t ${LPurple}w: ${LBlue}w displays information about currently logged in users and what each user is doing.${LGreen}\n" 
w
echo "\n\t\t ${LPurple}who: ${LBlue}Shows information about currently logged in user.${LGreen}\n"
who
echo "\n\t\t ${LPurple}whoami: ${LBlue}Shows the system’s username${LGreen}\n"
whoami
echo "\n\t\t ${LPurple}id: ${LBlue}This command is used to find out user and group names and numeric ID’s (UID or group ID) of the current user or any other user in the server.${LGreen}\n"
id
echo "\n\t\t ${LPurple}groups: ${LBlue}This command is used to display all the groups for which the user belongs to.${LGreen}\n"
groups
echo "\n\t\t ${LPurple}users: ${LBlue}Displays usernames of all users currently logged on the system.${LGreen}\n"
users
echo "\n\t\t ${LPurple}last: ${LBlue}Displays a list of all last logged in users. The list can be huge according to the number of user logins.${LGreen}\n"
last
echo "\n\t\t ${LPurple}lastlog: ${LBlue}This command is used to find the details of a recent login of all users or a particular user pass through as a flag.${LGreen}\n"
lastlog
echo "\n\t\t ${LPurple}date: ${LBlue}Shows date${LGreen}\n"
date
echo "\n\t\t ${LPurple}History: ${LBlue}History command shows all the previously used terminal commands in a list.${LGreen}\n"
history
